### ISSUE TITLE
Request: Reply-To

### ISSUE THREAD

**Issue by Muetze42** [gabrieliuga/laravel-mail-log#4]
Would it be possible to add "Reply-To" `->replyTo()` to the database for this package so that I don't have to adapt it all by myself?

Thanks

**Comment by gabrieliuga** [comment]
Hi Norman,

The CC, BCC fields are already saved in the message object. https://github.com/gabrieliuga/laravel-mail-log/blob/ffb742335a271cfa76a3b42b55fb5649230abb8a/src/Listeners/MailSentListener.php#L43

You should be able to access it via $mailLogModel->cc.
